name: "rig_0"
description: "Initial capture rig for tree dataset"

sensors:
  - name: "tof0"
    model: "vl53l8cx"
    sensor_type: "tof"

  - name: "tof1"
    model: "vl53l8cx"
    sensor_type: "tof"
