// The C++ port must agree with the Python original on recorded frames.
//
// The fixture was produced by isaaclab_pruning.baselines.tof_servo.deproject_tof
// on real recorded 8x8 grids from capture 21328323, so this compares the port
// against the implementation it claims to reproduce, not against itself.

#include <gtest/gtest.h>

#include <cmath>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "pruning_sil_cpp/tof_deprojection.hpp"

namespace
{

// A deliberately small JSON reader. The fixture is generated by this repository
// and has a fixed shape, so pulling in a JSON dependency would cost more than it
// is worth here.
std::string read_file(const std::string & path)
{
  std::ifstream stream(path);
  EXPECT_TRUE(stream.is_open()) << "fixture not found: " << path;
  std::stringstream buffer;
  buffer << stream.rdbuf();
  return buffer.str();
}

std::vector<double> numbers_after(const std::string & text, std::size_t from, std::size_t count)
{
  std::vector<double> values;
  std::size_t position = from;
  while (values.size() < count && position < text.size()) {
    while (position < text.size() &&
      !(std::isdigit(static_cast<unsigned char>(text[position])) || text[position] == '-'))
    {
      ++position;
    }
    if (position >= text.size()) {break;}
    std::size_t consumed = 0;
    values.push_back(std::stod(text.substr(position), &consumed));
    position += consumed;
  }
  return values;
}

}  // namespace

TEST(PinholeRays, AreUnitLengthAndSymmetric)
{
  const auto rays = pruning_sil_cpp::pinhole_rays(8, 8);
  ASSERT_EQ(rays.size(), 64u);
  for (const auto & ray : rays) {
    const double norm = std::sqrt(ray.x * ray.x + ray.y * ray.y + ray.z * ray.z);
    EXPECT_NEAR(norm, 1.0, 1e-12);
    EXPECT_GT(ray.z, 0.0) << "every zone must look forward";
  }
  // The grid is symmetric about its centre, so opposite corners mirror.
  EXPECT_NEAR(rays.front().x, -rays.back().x, 1e-12);
  EXPECT_NEAR(rays.front().y, -rays.back().y, 1e-12);
}

TEST(DeprojectToF, InvalidZonesCarryNoMeasurement)
{
  std::vector<double> ranges(64, 0.5);
  std::vector<bool> valid(64, true);
  valid[3] = false;
  valid[40] = false;

  const auto points = pruning_sil_cpp::deproject_tof(ranges, valid, {0.0, 0.0, 0.0}, 8, 8);
  ASSERT_EQ(points.size(), 64u);
  EXPECT_TRUE(pruning_sil_cpp::is_missing(points[3]));
  EXPECT_TRUE(pruning_sil_cpp::is_missing(points[40]));
  EXPECT_FALSE(pruning_sil_cpp::is_missing(points[0]));
  // An invalid zone must not silently become the sensor offset.
  EXPECT_FALSE(points[3].z == 0.0);
}

TEST(DeprojectToF, RejectsMismatchedInput)
{
  EXPECT_THROW(
    pruning_sil_cpp::deproject_tof({1.0}, std::vector<bool>(64, true), {0, 0, 0}, 8, 8),
    std::invalid_argument);
  EXPECT_THROW(pruning_sil_cpp::pinhole_rays(0, 8), std::invalid_argument);
}

TEST(DeprojectToF, MatchesThePythonImplementationOnRecordedFrames)
{
  const std::string path = std::string(PRUNING_SIL_CPP_FIXTURE_DIR) + "/tof_parity_fixture.json";
  const std::string text = read_file(path);

  std::size_t position = 0;
  int cases = 0;
  int compared = 0;

  while ((position = text.find("\"ranges_m\"", position)) != std::string::npos) {
    const auto ranges = numbers_after(text, position, 64);
    std::size_t valid_at = text.find("\"valid\"", position);
    ASSERT_NE(valid_at, std::string::npos);

    // Validity is true/false, so read it as text rather than as numbers.
    std::vector<bool> valid;
    std::size_t cursor = text.find('[', valid_at);
    const std::size_t end = text.find(']', cursor);
    while (valid.size() < 64) {
      const std::size_t t = text.find("true", cursor);
      const std::size_t f = text.find("false", cursor);
      if (t == std::string::npos && f == std::string::npos) {break;}
      if (t < f) {
        valid.push_back(true);
        cursor = t + 4;
      } else {
        valid.push_back(false);
        cursor = f + 5;
      }
      if (cursor > end + 1) {break;}
    }
    ASSERT_EQ(valid.size(), 64u);

    const std::size_t offset_at = text.rfind("\"offset_m\"", position);
    ASSERT_NE(offset_at, std::string::npos);
    const auto offset_values = numbers_after(text, offset_at, 3);
    ASSERT_EQ(offset_values.size(), 3u);

    const std::size_t expected_at = text.find("\"expected_points\"", position);
    ASSERT_NE(expected_at, std::string::npos);

    const auto points = pruning_sil_cpp::deproject_tof(
      ranges, valid, {offset_values[0], offset_values[1], offset_values[2]}, 8, 8);

    // Walk the expected list, treating null as "no measurement".
    std::size_t cursor_expected = text.find('[', expected_at);
    for (std::size_t zone = 0; zone < 64; ++zone) {
      cursor_expected = text.find('[', cursor_expected + 1);
      ASSERT_NE(cursor_expected, std::string::npos);
      const std::size_t triple_end = text.find(']', cursor_expected);
      const std::string triple = text.substr(cursor_expected, triple_end - cursor_expected);
      if (triple.find("null") != std::string::npos) {
        EXPECT_TRUE(pruning_sil_cpp::is_missing(points[zone]))
          << "zone " << zone << " should carry no measurement";
        continue;
      }
      const auto expected = numbers_after(triple, 0, 3);
      ASSERT_EQ(expected.size(), 3u);
      EXPECT_NEAR(points[zone].x, expected[0], 1e-9);
      EXPECT_NEAR(points[zone].y, expected[1], 1e-9);
      EXPECT_NEAR(points[zone].z, expected[2], 1e-9);
      ++compared;
      cursor_expected = triple_end;
    }
    ++cases;
    position = expected_at + 1;
  }

  EXPECT_EQ(cases, 10) << "fixture should cover five frames on both sensors";
  EXPECT_GT(compared, 200) << "parity must actually compare valid zones";
}
